### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by siddharth-1289-iiti** [Tangshitao/QuadTreeAttention#2]
Unable to import the following files:
score_computation_cuda and value_aggregation_cuda.
where are they defined?

**Comment by siddharth-1289-iiti** [comment]
Sorry, I should have run the '/QuadTreeAttention/setup .py' file, i.e., "python setup.py install". It's working now.

**Comment by ZhiWei-Liu123** [comment]
I have run the '/QuadTreeAttention/setup.py' file, but when I run the 'test_one_image_pair_sample.py ',erros occur as follows:
_**Traceback (most recent call last):
  File "test_one_image_pair_sample.py", line 8, in <module>
    from src.loftr import LoFTR
  File "/var/lzw/QuadTreeAttention/FeatureMatching/src/loftr/__init__.py", line 1, in <module>
    from .loftr import LoFTR
  File "/var/lzw/QuadTreeAttention/FeatureMatching/src/loftr/loftr.py", line 7, in <module>
    from .loftr_module import LocalFeatureTransformer, FinePreprocess
  File "/var/lzw/QuadTreeAttention/FeatureMatching/src/loftr/loftr_module/__init__.py", line 1, in <module>
    from .transformer import LocalFeatureTransformer
  File "/var/lzw/QuadTreeAttention/FeatureMatching/src/loftr/loftr_module/transformer.py", line 7, in <module>
    from .quadtree_attention import QuadtreeAttention
  File "/var/lzw/QuadTreeAttention/FeatureMatching/src/loftr/loftr_module/quadtree_attention.py", line 8, in <module>
    from QuadtreeAttention.modules.quadtree_attention import QTAttA, QTAttB
  File "../QuadTreeAttention/QuadtreeAttention/modules/quadtree_attention.py", line 10, in <module>
    from ..functions.quadtree_attention import score_computation_op, value_aggregation_op
  File "../QuadTreeAttention/QuadtreeAttention/functions/quadtree_attention.py", line 3, in <module>
    import score_computation_cuda
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory**_
Have you encountered this error and how did you solve it?
